clarify idle error and usage output
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1367267

This patch stops appending an "s" char to the end of an error message when an
incorrect resource type is provided. Adds a suggestion to use the
`get endpoints` command to this error output. Updates the Usage output
of `oc idle -h` to include SERVICE_ENDPOINTS instead of SERVICE --
having "SERVICE" before was misleading as it implied passing a service
resource to the command, instead of an endpoint name (e.g. I assumed I
would have to pass `oc idle svc/myappendpoint` instead of `oc idle
myappendpoint`.

```
$ oc idle dc/myappendpoint
error: no valid scalable resources found to idle: you must specify
endpoints, not deploymentconfigss
```

```
$ oc idle dc/myappendpoint
error: no valid scalable resources found to idle: you must specify
endpoints, not deploymentconfigs. View available endpoints
with "oc get endpoints"
```