pkg/oc/cli/admin/release: Add --insecure
Matching 'oc image mirror --insecure'.  This lets callers avoid:

  $ podman run -d -p 5000:5000 --name registry docker.io/library/registry
  $ oc adm release mirror --from=registry.svc.ci.openshift.org/openshift/origin-release:v4.0 --to localhost:5000/openshift-v4.0
  info: Mirroring 79 images to localhost:5000/openshift-v4.0 ...

  error: unable to connect to localhost:5000/openshift-v4.0: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
  ...
  error: unable to connect to localhost:5000/openshift-v4.0: Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client
  error: an error occurred during planning

when the local registry only speaks HTTP.

Ideally we could turn this off only for pushes, allowing us to pull
from a remote registry over HTTPS but push to the local registry over
HTTP.  But 'oc image mirror' doesn't seem to support that level of
granularity.  And even though the course --insecure allows access over
HTTP, we should still be using HTTPS where possible, so the risk of
leaking secrets from a properly-configured registry is small.
Although maybe there are increased man-in-the-middle risks?  I'm not
entirely clear on whether --insecure weakens our "acceptable" HTTPS
quality as well, or if it's just limited to the documented "allow
HTTPS too".

The contrib/completions/*/oc updates were generated with:

  $ make all WHAT=cmd/oc
  $ hack/update-generated-completions.sh