If Vagrant sets a hostname that doesn't resolve it breaks containerized installs
Currently if you launch a Fedora devenv in AWS this code wasn't even working.
Something silently fails and you end up with a hostname like ip-172-18-6-152.
However on RHEL7 it was working and openshiftdev.local didn't resolve from
within Docker containers.  This breaks the hack/test-end-to-end-docker.sh.

You get an error message like:

-----------
[INFO] Installing the registry
deploymentconfigs/docker-registry
services/docker-registry
[INFO] Verifying the docker-registry is up at 172.30.129.104
ERROR: gave up waiting for http://172.30.129.104:5000/healthz

[FAIL] !!!!! Test Failed !!!!
-----------

The reason it failed is because the Nodes can't find the Master to register
themselves.