[test/extended] Remove oc run --attach/--stdin which can't be dry-run flagged
$ oc run test1 --image=busybox --attach --dry-run
W0330 11:00:22.611725   19620 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
error: --dry-run=[server|client] can't be used with attached containers options (--attach, --stdin, or --tty)
See 'oc run -h' for help and examples

$ oc run test1 --image=busybox --stdin --dry-run
W0330 11:00:40.067325   19646 helpers.go:535] --dry-run is deprecated and can be replaced with --dry-run=client.
error: --dry-run=[server|client] can't be used with attached containers options (--attach, --stdin, or --tty)
See 'oc run -h' for help and examples