fix for image signature workflow end to end test
the following test is flaky in our e2e:

```
[sig-imageregistry][Serial] Image signature workflow can push a signed
image to openshift registry and verify it
```

after some investigations it seems like what is failing is the build
config
[here](https://github.com/openshift/origin/blob/release-4.18/test/extended/testdata/signer-buildconfig.yaml)

the failure is as follow:

```
STEP 4/8: RUN source /etc/os-release     && rhel_major=${VERSION_ID%.*}     && yum config-manager     --add-repo "https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi${rhel_major}/${rhel_major}/\$basearch/baseos/os/"     --add-repo "https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi${rhel_major}/${rhel_major}/\$basearch/appstream/os/"
ART yum/dnf wrapper [1]: Checking for CI build pod repo definitions...
ART yum/dnf wrapper [1]: Did not detect that this script is running in a CI build pod. Will not install CI repositories.
error: build error: building at STEP "RUN source /etc/os-release     && rhel_major=${VERSION_ID%.*}     && yum config-manager     --add-repo "https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi${rhel_major}/${rhel_major}/\$basearch/baseos/os/"     --add-repo "https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi${rhel_major}/${rhel_major}/\$basearch/appstream/os/"": while running runtime: exit status 6
```

this build config creates an image containing the following binaries:

- oc
- skopeo
- gpg2

with this pr we are now using the image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
as base image instead of quay.io/openshift/origin-cli:latest.