add a validateServiceAccount to the creation of ipfailover pods
make the 'oadm ipfailover' command act more like 'oadm router'.
Attempting to create an ipfailover pod without a priviliged sa
will now fail

$ oadm ipfailover ipf1 --credentials=openshift.local.config/master/openshift-router.kubeconfig --virtual-ips="10.66.127.100-101"  --service-account=new --dry-run
error: ipfailover could not be created; add "-systerm:serviceaccount:default:new" to scc priviledged

$ oadm ipfailover ipf1 --credentials=openshift.local.config/master/openshift-router.kubeconfig --virtual-ips="10.66.127.100-101"  --service-account=ipfailover --dry-run
--> Creating IP failover testing ...
    serviceaccount "ipfailover" created
    deploymentconfig "testing" created
--> Success (DRY RUN)

changelog:

fix typos

changed validateServiceAccount to check for the required permissions
instead of the privileged service account name

deprecate credentials

error message to make sense from validateServiceAccount

changed the end-to-end test to reflect my changes

autogenerated ipfailover doc changes

updated the tests in test/cmd/router.sh