extract_tools: avoid error with --command
`oc adm extract --command=openshift-install` errors with:

  error: image did not contain usr/bin/openshift-install

when, in fact, it succeeds in extracting the binary.

Turns out we're not tracking successful extraction in this case.