pkg/oc/cli/admin/release: Local interpret-trailers
Until our CI suite gets Git 2.2.0 or later and the interpret-trailers
command, so we don't get [1]:

  <testcase name="TestCommitProcess/no_trailers" time="0.01">
    <failure message="=== RUN   TestCommitProcess/no_trailers&#xA;    --- FA ...">=== RUN   TestCommitProcess/no_trailers&#xA;    --- FA ...</failure>
    <system-out>=== RUN   TestCommitProcess/no_trailers&#xA;    --- FAIL: TestCommitProcess/no_trailers (0.01s)&#xA;    &#x9;git_test.go:98: exit status 1&#xA;</system-out>
  </testcase>

once we get a more recent Git (2.2.0 is 2014-11-26!), we can revert
this commit to get Git's more robust handling.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/22186/pull-ci-openshift-origin-master-unit/3767/artifacts/unit/unit_report_6x2xq.xml